### PR TITLE
managers.py: issues with entry_id

### PR DESCRIPTION
**Pull request by mortenwh**
See comments in the code for explanations.

### CODE REVIEW

**Comment by akorosov** [comment]
@mortenwh , I generally agree with your edits. Did you test it?

**Comment by mortenwh** [comment]
yes, it is tested - see  `geospaas/nansat_ingestor/tests.py`. I also added another test to check an error I had problems with. Conclusion is added at the end of the test. I will remove the comments as well.

**Comment by mortenwh** [comment]
I thought I could fix this in my own code - but it seems `geospaas.nansat_ingestor.managers` needs to be changed. I'll add a commit...

**Comment by mortenwh** [comment]
No.. `nansat.domain.Domain.get_border` should be changed to have a maximum of, e.g., 4 decimal points for the lon/lat values - is that sufficient?

**Pull request merged**
